/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static java.lang.Integer.MAX_VALUE;
import static java.lang.Integer.MIN_VALUE;
import static org.junit.Assert.*;

public class MultiplyTest {
    @Test
    public void positiveTest() {
       Calculator calculator = new Calculator();
        assertEquals(Long.valueOf(0), Long.valueOf(calculator.multiply.apply(-9,0)));
    }
    @Test
    public void negativeTest() {
        Calculator calculator = new Calculator();
        assertTrue("В математике такое выражение является истинным, однако в javа первый аргумент при становится равным MIN_VALUE",
                calculator.multiply.apply(MAX_VALUE + 1, MIN_VALUE) < 0);
    }
    @Test
    public void compareMinMaxTest() {
        assertEquals(MIN_VALUE, MAX_VALUE + 1);
    }
}
